# Generated by Django 4.2.2 on 2023-07-10 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_tags_products_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='color',
        ),
    ]
