# Generated by Django 4.2.2 on 2023-07-11 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_catalogue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Catalogue',
        ),
    ]
