# Generated by Django 4.2.2 on 2023-07-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_company_logo_products_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='catalogue',
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
